name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      # NOTE: install deps for ci
      # - name: install_dependencies
      #   run:

      - name: Check Tools
        run: rustup show

      - name: Check Format
        run: rustup component add rustfmt --toolchain 1.64.0-x86_64-apple-darwin && cargo fmt --check

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test
